os: linux
dist: xenial
language: elixir

cache:
  directories:
    - _build
    - deps

jobs:
  include:
    - &test
      stage: test
      elixir: 1.7.4
      otp_release: 19.3
      addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-client-9.6
            - postgresql-server-dev-9.6
      before_install: |-
        export PG_CONFIG=/usr/lib/postgresql/9.6/bin/pg_config

        wget -q 'https://github.com/RhodiumToad/ip4r/archive/2.4.1.tar.gz'
        tar -xzf 2.4.1.tar.gz

        pushd ip4r-2.4.1 > /dev/null
          make && sudo make install
        popd > /dev/null
      before_script:
        - psql -c "CREATE EXTENSION ip4r;" -U postgres
        - psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'postgres';" -U postgres
    - <<: *test
      elixir: 1.8.2
      otp_release: 20.3
    - <<: *test
      elixir: 1.9.4
      otp_release: 21.3
    - <<: *test
      elixir: 1.10.4
      otp_release: 22.3
    - <<: *test
      elixir: 1.10.4
      otp_release: 23.0
      after_success: mix coveralls.travis

    - stage: code quality
      elixir: 1.10.4
      otp_release: 23.0
      script:
        - mix format --check-formatted
        - mix credo --strict
